### ISSUE TITLE
Fail to update on gnome-shell 43.3

### ISSUE THREAD

**Issue by bartoszek** [ztefn/gse-haguichi-indicator#1]
I'm experiencing an update problem after the gnome-shell 43.3 update.
I'm getting message about `haguashi getting an update in next login session`
![Zrzut ekranu z 2023-03-21 11-42-39](https://user-images.githubusercontent.com/1213348/226584759-9118c048-4feb-4d14-b607-31f0ba3b0545.png)

But each consecutive login fails with `journal` showing `JS error` about the failed update of `haguashi` because of the nonempty `icon` folder.
```log
mar 21 10:53:18 grafZero gnome-shell[894950]: Failed to install extension updates for .gse-haguichi-indicator@ztefn.github.com
mar 21 10:53:18 grafZero gnome-shell[894950]: JS ERROR: Gio.IOErrorEnum: Błąd podczas usuwania pliku /home/bartus/.local/share/gnome-shell/extension-updates/.gse-haguichi-indicator@ztefn.github.com/icons: Katalog nie jest pusty
                                              recursivelyDeleteDir@resource:///org/gnome/shell/misc/fileUtils.js:48:13
                                              recursivelyDeleteDir@resource:///org/gnome/shell/misc/fileUtils.js:44:33
                                              _installExtensionUpdates/<@resource:///org/gnome/shell/ui/extensionSystem.js:588:27
                                              collectFromDatadirs@resource:///org/gnome/shell/misc/fileUtils.js:28:28
                                              _installExtensionUpdates@resource:///org/gnome/shell/ui/extensionSystem.js:574:19
                                              init@resource:///org/gnome/shell/ui/extensionSystem.js:56:14
                                              _initializeUI@resource:///org/gnome/shell/ui/main.js:309:22
                                              start@resource:///org/gnome/shell/ui/main.js:186:5
                                              @resource:///org/gnome/shell/ui/init.js:6:17
mar 21 10:53:18 grafZero gnome-shell[894950]: Execution of main.js threw exception: Module resource:///org/gnome/shell/ui/init.js threw an exception
```
Removing the `icons` folder gets me back at square on.

**Comment by ztefn** [comment]
I experienced the same thing on my Arch test machine and hoped something was just messed up locally on that machine. Unfortunately it appears something is completely broken with the GNOME shell extension updates process. I found these identical issues:

- https://bugs.launchpad.net/ubuntu/+source/gnome-shell/+bug/1998963
- https://bbs.archlinux.org/viewtopic.php?id=282470
- https://github.com/tuberry/extension-list/issues/15

The third issue reports the issue is triggered by symbolic links. Haguichi indicator uses a symbolic links for the [haguichi-connecting-3-symbolic.svg](https://github.com/ztefn/gse-haguichi-indicator/blob/master/gse-haguichi-indicator%40ztefn.github.com/icons/haguichi-connecting-3-symbolic.svg) icon. I will drop the symbolic link for this icon and push a new update to [extensions.gnome.org](https://extensions.gnome.org/). It will have to await review before being published. For now I have disabled version 20 so that update should be held back from now on.

**Comment by ztefn** [comment]
The updated version is already live on [extensions.gnome.org](https://extensions.gnome.org/). It was [auto-approved](https://extensions.gnome.org/review/39408) (probably because there were no code changes).

However this update will likely still fail, because the issue is with the old version its trying to delete. So you will need to remove both the update (in ~.local/share/gnome-shell/**extension-updates**/) and extension itself (in ~.local/share/gnome-shell/**extensions**/). And then reinstall it, making sure its version 21. Next time in the future when there is an update it should work without issues 🤞️.

**Comment by bartoszek** [comment]
Thanks for the exhaustive explanation 🥲
